export const productsArray = [
  {
    title: 'рис',
    description: 'вареный',
    fats: 0.7,
    proteins: 6.7,
    carbohydrates: 78.9,
    price: 1,
    weight: 105,
    image: 'rice.png',
  },
  {
    title: 'борщ',
    description: 'красный',
    fats: 21.8,
    proteins: 6.2,
    carbohydrates: 25,
    price: 1.8,
    weight: 524,
    image: 'image.png',
  },
  {
    title: 'котлета',
    description: 'куриная',
    fats: 16.7,
    proteins: 31.2,
    carbohydrates: 7.8,
    price: 2,
    weight: 180,
    image: 'chiken_cutlet.png',
  },
  {
    title: 'котлета',
    description: 'рыбная',
    fats: 6.2,
    proteins: 17.6,
    carbohydrates: 3.6,
    price: 1.7,
    weight: 118,
    image: 'fish_cutlet.png',
  },
  {
    title: 'компот',
    description: 'вишнёвый',
    fats: 0.1,
    proteins: 0.3,
    carbohydrates: 16.5,
    price: 0.6,
    weight: 252,
    image: 'cherry_juice.png',
  },
  {
    title: 'пирожок',
    description: 'с яйцом и луком',
    fats: 7.4,
    proteins: 5.1,
    carbohydrates: 24.9,
    price: 1.1,
    weight: 76,
    image: 'image.png',
  },
];
